name: Building Program (Tianlu)
run-name: Building ${{ GITHUB.REPOSITORY }} (Tianlu)

on:
  workflow_dispatch:

jobs:
  call:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-tianlu.yml@master
    secrets: inherit
